const mongoose = require("mongoose");
const { Schema } = mongoose;

// ==============================
// Guest Cart Schema Definition
// ==============================
const guestCartSchema = new Schema(
  {
    // Session ID to identify guest users (generated by frontend or server)
    sessionId: { 
      type: String, 
      required: true,
      index: true // Index for faster queries
    },

    // Reference to the main item/product
    item: { type: Schema.Types.ObjectId, ref: "Item", required: true },

    // Size from the item's sizes
    size: { type: String, required: true },

    // SKU (Stock Keeping Unit) representing a unique variation (size combination)
    sku: { type: String, required: true },

    // Quantity of the item in the cart (must be at least 1)
    quantity: { type: Number, default: 1, min: 1 },

    // Optional: Device identifier for better session tracking
    deviceId: { type: String },

    // TTL (Time To Live) - auto-delete guest carts after 30 days
    expiresAt: { 
      type: Date, 
      default: Date.now, 
      expires: 30 * 24 * 60 * 60 // 30 days in seconds
    }
  },
  {
    timestamps: true,      // Adds createdAt and updatedAt fields automatically
    versionKey: false      // Disables the __v version key used by Mongoose
  }
);

// ==============================
// Indexes for Performance
// ==============================
guestCartSchema.index({ sessionId: 1, item: 1, sku: 1 }); // Composite index for finding specific items
guestCartSchema.index({ expiresAt: 1 }); // TTL index

// ==============================
// Validation Middleware
// ==============================
// Before saving, validate that the SKU and size exist within the associated Item
guestCartSchema.pre("save", async function (next) {
  const item = await mongoose.model("Item").findById(this.item);

  // Check if item is valid
  if (!item) {
    return next(new Error("Invalid Item reference"));
  }

  // Check if the provided size and SKU exist in the item's sizes
  const sizeVariant = item.sizes.find(size => 
    size.size === this.size && size.sku === this.sku
  );

  if (!sizeVariant) {
    return next(new Error("Invalid size or SKU provided"));
  }

  next();
});

// ==============================
// Static Methods
// ==============================

// Transfer guest cart to user cart after authentication
guestCartSchema.statics.transferToUser = async function(sessionId, userId) {
  try {
    const Cart = mongoose.model("Cart");
    const guestItems = await this.find({ sessionId });
    
    for (const guestItem of guestItems) {
      // Check if user already has this item in cart
      const existingCartItem = await Cart.findOne({
        user: userId,
        item: guestItem.item,
        sku: guestItem.sku
      });

      if (existingCartItem) {
        // Merge quantities
        existingCartItem.quantity += guestItem.quantity;
        await existingCartItem.save();
      } else {
        // Create new cart item for user
        const newCartItem = new Cart({
          user: userId,
          item: guestItem.item,
          size: guestItem.size,
          sku: guestItem.sku,
          quantity: guestItem.quantity
        });
        await newCartItem.save();
      }
    }

    // Delete guest cart items after transfer
    await this.deleteMany({ sessionId });
    
    return { success: true, transferredItems: guestItems.length };
  } catch (error) {
    console.error("Error transferring guest cart:", error);
    return { success: false, error: error.message };
  }
};

// Export the GuestCart model
module.exports = mongoose.model("GuestCart", guestCartSchema);
