const mongoose = require('mongoose');
const { Schema } = mongoose;

// ==============================
// Guest Wishlist Schema Definition
// ==============================
const guestWishlistSchema = new Schema(
  {
    // Session ID to identify guest users (generated by frontend or server)
    sessionId: { 
      type: String, 
      required: true,
      index: true // Index for faster queries
    },

    // Reference to the item in the wishlist
    item: { 
      type: Schema.Types.ObjectId, 
      ref: "Item", 
      required: true 
    },

    // Optional: Device identifier for better session tracking
    deviceId: { type: String },

    // TTL (Time To Live) - auto-delete guest wishlists after 30 days
    expiresAt: { 
      type: Date, 
      default: Date.now, 
      expires: 30 * 24 * 60 * 60 // 30 days in seconds
    }
  },
  { 
    timestamps: true, // Automatically adds createdAt and updatedAt fields
    versionKey: false // Disables the "__v" version key
  }
);

// ==============================
// Indexes for Performance
// ==============================
guestWishlistSchema.index({ sessionId: 1, item: 1 }); // Composite index for finding specific items
guestWishlistSchema.index({ expiresAt: 1 }); // TTL index

// ==============================
// Static Methods
// ==============================

// Transfer guest wishlist to user wishlist after authentication
guestWishlistSchema.statics.transferToUser = async function(sessionId, userId) {
  try {
    const Wishlist = mongoose.model("Wishlist");
    const guestItems = await this.find({ sessionId });
    
    for (const guestItem of guestItems) {
      // Check if user already has this item in wishlist
      const existingWishlistItem = await Wishlist.findOne({
        user: userId,
        item: guestItem.item
      });

      if (!existingWishlistItem) {
        // Create new wishlist item for user
        const newWishlistItem = new Wishlist({
          user: userId,
          item: guestItem.item
        });
        await newWishlistItem.save();
      }
    }

    // Delete guest wishlist items after transfer
    await this.deleteMany({ sessionId });
    
    return { success: true, transferredItems: guestItems.length };
  } catch (error) {
    console.error("Error transferring guest wishlist:", error);
    return { success: false, error: error.message };
  }
};

// Export the GuestWishlist model
module.exports = mongoose.model("GuestWishlist", guestWishlistSchema);
